name: CI Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV
          echo "RELEASE_FILE=git_copyright_${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_ENV

      - name: Build in release mode
        run: cargo build --release
      - name: List build content
        run: ls -la
 
      - name: Compress release files
        run: tar -czf ${RELEASE_FILE} target/release/git* target/release/lib*
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish a release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@69a9b03fd9694e185b5d1450f1c534fb50ed4ab8
        with:
          files: |
            *.tar.gz

  docker_build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -f Dockerfile --tag "sgasse/git_copyright:${VERSION}" .

      - name: Login to Docker
        run: docker login -u sgasse -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push "sgasse/git_copyright:${VERSION}"
